# syntax=docker/dockerfile:1

FROM node:lts-alpine AS builder
WORKDIR /src
COPY package*.json ./
RUN npm install --only=production
COPY . .
RUN npm run build

FROM node:lts-alpine
WORKDIR /app
COPY package*.json ./

ARG SUNO_COOKIE=eyJhbGciOiJSUzI1NiIsImNhdCI6ImNsX0I3ZDRQRDExMUFBQSIsImtpZCI6Imluc18yT1o2eU1EZzhscWRKRWloMXJvemY4T3ptZG4iLCJ0eXAiOiJKV1QifQ.eyJhdWQiOiJzdW5vLWFwaSIsImF6cCI6Imh0dHBzOi8vc3Vuby5jb20iLCJleHAiOjE3MzMxNTc2NDYsImZ2YSI6Wy0xLC0xXSwiaHR0cHM6Ly9zdW5vLmFpL2NsYWltcy9jbGVya19pZCI6InVzZXJfMloxVzU5Y3phY2h5ajdIMnFzbTVxWWRMOWlyIiwiaHR0cHM6Ly9zdW5vLmFpL2NsYWltcy9lbWFpbCI6ImNyaXN0aWFub2FyZWRlczA5QGdtYWlsLmNvbSIsImh0dHBzOi8vc3Vuby5haS9jbGFpbXMvcGhvbmUiOm51bGwsImlhdCI6MTczMzE1NzU4NiwiaXNzIjoiaHR0cHM6Ly9jbGVyay5zdW5vLmNvbSIsImp0aSI6Ijc5NGExMDljZTQyNWU2ZjI2OTQyIiwibmJmIjoxNzMzMTU3NTc2LCJzaWQiOiJzZXNzXzJtN2FzZ2ZYczFpVE55NmMxR2tjcldSR1c0MSIsInN1YiI6InVzZXJfMloxVzU5Y3phY2h5ajdIMnFzbTVxWWRMOWlyIn0.IUWazEaobHx8xwMuVHXUnchY7hbZaoWAixM5XDxOMTvXbo-rklIBooIBUX_bqJSuDg6eydPKvJn9fZgIScy_EBaKYxYu0eb0vZE85npwQ_QAu0KBY3dHHWkJZf-0wJ66jr7x32t7FLZf_Tf2r5m9pgcacyWRpf-VZw5AugE4S8CDJGGYY5M9bCoJsyv48EMyBu_ZYEtHdLCQ6sGZuoXgLzyA-jmr2L3_LfMMMBr4YiPKe_4imYlLy3M1xnORaWFwtlWzF6fUIIK784ZUwxxuwvdzqkIqpiaeLZQK23nqRVjpSXnxpkCFoaYuktn2ZRQY-G260SO_XfBF3jmulkjzlA
RUN if [ -z "$SUNO_COOKIE" ]; then echo "SUNO_COOKIE is not set" && exit 1; fi
ENV SUNO_COOKIE=${SUNO_COOKIE}

RUN npm install --only=production
COPY --from=builder /src/.next ./.next
EXPOSE 3000
CMD ["npm", "run", "start"]
